spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

jwt:
  access-token-expiration: 1800000 #30?
  secret: ${JWT_SECRET}
