INSERT INTO book (title, author)
VALUES ('The Silent Echo', 'Alice Johnson'),
       ('Whispers of the Wind', 'Michael Smith'),
       ('The Last Dawn', 'Emily Carter'),
       ('Echoes of Time', 'Daniel Brown'),
       ('Falling Stars', 'Sophia Miller'),
       ('The Hidden Truth', 'James Wilson'),
       ('Shadows of the Past', 'Olivia Martin'),
       ('The Secret Garden', 'Benjamin Adams'),
       ('Lost in the City', 'Emma Thomas'),
       ('The Dark Horizon', 'William Anderson'),
       ('A Journey Unknown', 'Charlotte White'),
       ('Tales of the Moon', 'Henry Harris'),
       ('The Burning Light', 'Isabella Clark'),
       ('Beyond the Mountains', 'Ethan Lewis'),
       ('A Whispering Shadow', 'Mia Walker'),
       ('The Forgotten Legend', 'Alexander Hall'),
       ('Crimson Skies', 'Grace Young'),
       ('Frozen Memories', 'David King'),
       ('The Vanished Path', 'Sophia Wright'),
       ('The Eternal Flame', 'Liam Scott'),
       ('Mysteries of the Ocean', 'Amelia Baker'),
       ('Echo in the Silence', 'Ella Carter'),
       ('The Shattered Mirror', 'Nathan Green'),
       ('Into the Abyss', 'Olivia Turner'),
       ('A Flickering Hope', 'Lucas Edwards'),
       ('Dreams of Yesterday', 'Madeline Parker'),
       ('The Guardian’s Oath', 'Matthew Collins'),
       ('Fragments of Destiny', 'Chloe Mitchell'),
       ('Under a Blood Moon', 'Ryan Ross'),
       ('The Lost Symphony', 'Ava Sanders'),
       ('The Silver Lining', 'Samuel Ramirez'),
       ('A Dance with Fate', 'Hannah Hughes'),
       ('Cursed by the Stars', 'Owen Price'),
       ('Footsteps in the Fog', 'Sophia Bailey'),
       ('The Wandering Spirit', 'Jackson Cooper'),
       ('Torn Between Worlds', 'Lily Morgan'),
       ('The Hidden Talisman', 'Daniel Bell'),
       ('Beneath the Surface', 'Emma Murphy'),
       ('Chronicles of the Unknown', 'Michael Reed'),
       ('Echoes from the Deep', 'Victoria Peterson'),
       ('A Tale of Two Souls', 'Ethan Howard'),
       ('The Shadow’s Curse', 'Emily Ward'),
       ('The Unfinished Story', 'Mason Brooks'),
       ('A Song for the Broken', 'Grace Bennett'),
       ('The Midnight Hour', 'Carter Rivera'),
       ('The Raven’s Cry', 'Sophia Flores'),
       ('Bound by Destiny', 'Logan Gonzalez'),
       ('The Final Chapter', 'Scarlett Torres');
