name: cd

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: 기존 어플리케이션을 종료한다
        shell: bash {0}
        run: |
          PID=$(lsof -t -i:8080) || true
          if [ -n "$PID" ]; then
            echo "기존 애플리케이션 종료: $PID"
            kill -9 $PID
          else
            echo "8080 포트에서 실행 중인 프로세스가 없습니다."
          fi

      - name: JAR 파일 복사
        shell: bash {0}
        run: |
          mkdir -p /home/ubuntu/backend
          cp -f build/libs/*.jar /home/ubuntu/backend/

      - name: 빈 포트에 새 어플리케이션 실행
        working-directory: /home/ubuntu/backend
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          nohup java -Duser.timezone=Asia/Seoul -jar \
          $(ls -t /home/ubuntu/backend/*.jar | head -n 1) &
